export const employeesData = [
  {
    id: 1,
    name: "John",
    role: "Intern",
    salary: 45000,
    status: "Part time (PT)",
    workModel: "On-Site",
    yoe: 2,
    active: false,
    favoriteOfficeSupply: "Stapler",
    hobbies: ["hiking", "golf", "stamp collection"],
    avatar: "../images/spongebob-characters-sheet-1.png"
  },
  {
    id: 2,
    name: "Cristy",
    role: "Art Director",
    salary: 105000,
    status: "Full time (FT)",
    workModel: "Hybrid",
    yoe: 4,
    active: true,
    favoriteOfficeSupply: "Tablet",
    hobbies: ["knitting", "fishing", "scrapbooking"],
    avatar: "../images/spongebob-characters-sheet-2.png"
  },
  {
    id: 3,
    name: "David",
    role: "Office Manager",
    salary: 110000,
    status: "Full time (FT)",
    workModel: "On-Site",
    yoe: 6,
    active: true,
    favoriteOfficeSupply: "Rubber-band",
    hobbies: ["pc gaming", "wine tasting", "gardening"],
    avatar: "../images/spongebob-characters-sheet-3.png"
  },
  {
    id: 4,
    name: "Blue",
    role: "Office Doggo",
    salary: 50,
    status: "Part time (PT)",
    workModel: "Hybrid",
    yoe: 3,
    active: false,
    favoriteOfficeSupply: "USB Drive",
    hobbies: ["chasing butterflies", "chewing sandals", "looking clueless"],
    avatar: "../images/spongebob-characters-sheet-4.png"
  },
  {
    id: 5,
    name: "Jenna",
    role: "Accountant",
    salary: 122000,
    status: "Full time (FT)",
    workModel: "Hybrid",
    yoe: 5,
    active: false,
    favoriteOfficeSupply: "Post-it Notes",
    hobbies: ["shopping", "netflix", "cooking"],
    avatar: "../images/spongebob-characters-sheet-5.png"
  },
  {
    id: 6,
    name: "Ulrich",
    role: "Web Developer",
    salary: 145000,
    status: "Full time (FT)",
    workModel: "Remote",
    yoe: 8,
    active: true,
    favoriteOfficeSupply: "Sharpie",
    hobbies: ["programming", "rock climbing", "photography"],
    avatar: "../images/spongebob-characters-sheet-6.png"
  },
  {
    id: 7,
    name: "Kimberly",
    role: "Graphic Designer",
    salary: 85000,
    status: "Full time (FT)",
    workModel: "Hybrid",
    yoe: 4,
    active: true,
    favoriteOfficeSupply: "Pantone swatch book",
    hobbies: ["swimming", "baking", "decorating"],
    avatar: "../images/spongebob-characters-sheet-7.png"
  },
  {
    id: 8,
    name: "Shanaynay",
    role: "Backup dancer",
    salary: 35000,
    status: "Part time (PT)",
    workModel: "On-Site",
    yoe: 8,
    active: true,
    favoriteOfficeSupply: "Wig",
    hobbies: ["dancing", "doing makeup", "shopping"],
    avatar: "../images/spongebob-characters-sheet-8.png"
  },
  {
    id: 9,
    name: "Mitch Van Buren",
    role: "Solo Guitarist",
    salary: 135000,
    status: "Full time (FT)",
    workModel: "Hybrid",
    yoe: 11,
    active: false,
    favoriteOfficeSupply: "Gibson guitar",
    hobbies: ["Rock 'n rolling", "Touring concerts", "visiting Guitar Center"],
    avatar: "../images/spongebob-characters-sheet-9.png"
  },
  {
    id: 10,
    name: "Earl",
    role: "Fortune Cookie Consultant",
    salary: 0,
    status: 'unknown', 
    workModel: "Remote",
    yoe: 10,
    active: true,
    favoriteOfficeSupply: "Girl Scout Cookies",
    hobbies: ["Yoga", "ASMR", "Baking"],
    avatar: "../images/spongebob-characters-sheet-10.png"
  }
];

// console.log(employeesData.length);
